No need to use VERSION file
The VERSION file is useless and raise exception when using Kitchen:
ERROR: No such file or directory - /tmp/kitchen/cookbooks/augeas/VERSION
It would be better to remove him and use only metadata.rb to
retrieve the version of the cookbook.